### ISSUE TITLE
Do not run rclone command on startup, only on cron

### ISSUE THREAD

**Issue by hongkongkiwi** [openbridge/ob_bulkstash#10]
Firstly thank you for this awesome docker!

The docker image complains if I set the rclone schedule but do not want to set the command to run on startup.

For example, in the case where I only want to run on schedule and not immediately I have no option (docker-entrypoint complains that I havn't passed any arguments).

Can we make this an option? something like RCLONE_CROND_RUN_ON_STARTUP

**Comment by tspicer** [comment]
Hi,
I might need to understand your use case a little better. Can you provide some actual samples of what you are running? 

Isn't the schedule, or when someting is run, determined by your crond runtime? Something like this is **not** going to run at startup `0 10 1-3 * *` or even `0 * * * *` which will run every hour. 

Why does the image will complain? `crond` needs certain things to run correctly. This is especially true depending on what you want to run under cron. For example, `crond` does not normally have access to environment variables for things it runs, so you need to make it aware of them. See the `rclone.sh` file for some context.

I updated a few parts of the crond docs. Specficially, it describes the best approach to running cron in a container.  If you set a crond config file, crond will be started as a background process. Check the README. 

Also, you could always run arbitrary commands as you see fit. You can even mount your own script and have it run at startup. The docker-entry file accepts what you tell it to run, though you need to understand how Docker runs things (or doesnt run them). Check out the [docker run docs](https://docs.docker.com/engine/reference/commandline/run/) for the latest syntax.

Here is a simple example of jumping into bash:
```
docker run -it --name rclone openbridge/ob_bulkstash:latest bash
```
Run crond in the foreground:
```
docker run -it --name rclone openbridge/ob_bulkstash:latest crond -f
```
In the [docker-compose example](https://github.com/openbridge/ob_bulkstash/blob/develop/docker-compose.yml) you can see the command used is bash. 

Lastly, you can run just about any command you want at startup or when the container is running. For example, lets say I just want to exec into a running container and drop to `bash`, then I can use:

```bash
docker exec -it rclone bash
```
Lets say I want to inspect the health of the container via Monit:
```bash
docker exec -it rclone monit status
```
This will show me the status of the container:
```
Monit 5.25.1 uptime: 5m

Process 'crond'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  pid                          12
  parent pid                   1
  uid                          0
  effective uid                0
  gid                          0
  uptime                       5m
  threads                      1
  children                     0
  cpu                          0.0%
  cpu total                    0.0%
  memory                       0.0% [44 kB]
  memory total                 0.0% [44 kB]
  security attribute           (null)
  disk write                   0 B/s [8 kB total]
  data collected               Sun, 25 Nov 2018 19:48:39

System 'b355cfc4834d'
  status                       OK
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  load average                 [0.13] [0.17] [0.10]
  cpu                          0.5%us 1.0%sy 0.0%wa
  memory usage                 889.7 MB [11.2%]
  swap usage                   0 B [0.0%]
  uptime                       5d 23h 23m
  boot time                    Mon, 19 Nov 2018 20:25:02
  data collected               Sun, 25 Nov 2018 19:48:39
```
