### ISSUE TITLE
environment variable for time zone?

### ISSUE THREAD

**Issue by Chovin** [openbridge/ob_bulkstash#13]
there's no environment variable to set the timezone used by crond.
I needed to mount a file to `/etc/localtime`. Is this the preferred way to do it?

**Comment by Chovin** [comment]
using this as the command in docker-compose seems to do the trick as well when setting a TZ env
```Dockerfile
command: /bin/bash -c "apk add tzdata
      && mv /usr/share/zoneinfo/$TZ /etc/localtime 
      && apk del tzdata
      && tail -f /dev/null"
```

**Comment by tspicer** [comment]
tzdata can get added to the base image if needed

**Comment by lukasmrtvy** [comment]
@tspicer  I think that You should add tzdata package to baseimage, its backward compatible and it will support addtional timezones.

**Comment by tspicer** [comment]
added the `tzdata` per popular request though the @chovin approach is likely the better model going forward as it keeps the base image smaller and allows an end user to select the packages to included beyond the base.
