### ISSUE TITLE
RCLONE_CROND_SCHEDULE in docker-entrypoint.sh is not considered

### ISSUE THREAD

**Issue by lukasmrtvy** [openbridge/ob_bulkstash#17]
There https://github.com/openbridge/ob_bulkstash/blob/develop/docker-entrypoint.sh#L32 should be `RCLONE_CROND_SCHEDULE` instead of `RCLONE_SYNC_COMMAND`, isnt it ?

**Comment by tspicer** [comment]
`RCLONE_SYNC_COMMAND` is correct. The docs reference numerous examples of using this command. If you are attempting to use the utility script `rclone.sh` you should modify it as needed.  You would likely want to mount your CRON file per the docs.

As I said in the other ticket, I would advise not running `rclone.sh` as it is not needed in many cases. It is only present to highlight running an internal process (ie checking folder size) and then running some commands. This is only an example, not a recommended run time model.

**Comment by lukasmrtvy** [comment]
@tspicer 
I am not sure, so what is proper command for running it crond + monit with custom scheduled option ? I dont want to provide my own crontab config nor command wrapper. I need to run only one job, under one folder, periodicaly.

**Comment by tspicer** [comment]
Why not follow one of the examples provided? You set a schedule and then run your commands. Instead of `/usr/bin/env bash -c /foo run` it can be whatever. Mount a script, run the rclone copy commands....
```
docker run -d -e RCLONE_SYNC_COMMAND="*/15 * * * * /usr/bin/env bash -c /foo run" openbridge/ob_bulkstash crond -f
```

**Comment by lukasmrtvy** [comment]
There is no monit running with this example. Crond has usually problem with zombie processes.

**Comment by tspicer** [comment]
How does monit help with zombie processes? Do you want monit to be the primary background process?

**Comment by tspicer** [comment]
BTW, did you see the `/rcron.sh` script? You can always use something like that.
