### ISSUE TITLE
Support for Secrets

### ISSUE THREAD

**Issue by efrecon** [openbridge/ob_bulkstash#3]
According to the [doc](https://docs.docker.com/engine/swarm/secrets/)

> you can use Docker secrets to centrally manage this data and securely transmit it to only those containers that need access to it. Secrets are encrypted during transit and at rest in a Docker swarm. A given secret is only accessible to those services which have been granted explicit access to it, and only while those service tasks are running.

PR #2 provides support for carrying secretive information such as tokens or passwords for the sources and destinations using secrets. This follows the idea of the image itself, an image with a strong focus on configuration through environment variables (and not a configuration file, even if this is still possible). The PR achieves this through looking into the content of environment variables and resolving those that follow a given template to the file that it points at. This is slightly different from the "regular" Docker way. Official images use `_FILE` at the end of environment variables to take information from a file instead. However, as the variables are read by `rclone`, the mechanism in the PR provides a solution that does not imply any modification of the `rclone` binary implementation, thus will be able to work in future version of rclone.

Would you mind considering taking in the PR?

**Comment by tspicer** [comment]
Merged. Thanks!
