### ISSUE TITLE
Tagging the image per the rclone version

### ISSUE THREAD

**Issue by efrecon** [openbridge/ob_bulkstash#4]
As shown in a similar [project](https://github.com/tynor88/docker-rclone), Docker hub [hooks](https://docs.docker.com/docker-cloud/builds/advanced/) can be used to automatically generate images with all the official versions of rclone, tagged with the version number of rclone. This allow to pick up specific versions of rclone in production.

Would you be interested in a PR achieving this? For a longer discussion and history, see [here](https://github.com/tynor88/docker-rclone/issues/5).

**Comment by tspicer** [comment]
I like the idea. Happy to accept a PR for this. Thanks.

**Comment by tspicer** [comment]
Decided to grab the referenced changes and updated. Thanks!

**Comment by efrecon** [comment]
Great! I was off for Easter...
