### ISSUE TITLE
Add quiet mode for docker entrypoint

### ISSUE THREAD

**Issue by nixikanius** [openbridge/ob_bulkstash#5]
First of all, I want to thank the contributors of this useful docker image for rclone. Unlike other images, this one can be used not only with sync command but also with all other rclone abilities. Coupled with a flexible configuration with environment variables, ob_bulkstash is an excellent instrument for everyday life of DevOps engineers.

While using ob_bulkstash in my life I severely lack a quiet mode for docker entrypoint. The reason here is that I use rclone in the everyday logrotate scenario which runs via cron. All of my servers are tuned to send me emails if some tool outputs anything in cron jobs (think, this is usual for the whole industry). This fact leads to receiving similar emails with info messages about ob_bulkstash normal work every day, when I should receive messages only if some command falls down.

Here is my example of ob_bulkstash run and its output which obstructs me:

```
# docker run --rm --name=rclone-move-logs -v /path/to/logs:/data/path/to/logs -e RCLONE_CROND_SOURCE_PATH="" -e RCLONE_CROND_DESTINATION_PATH="" -e RCLONE_CONFIG_STORAGE_TYPE="s3" -e RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID=$RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID -e RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY=$RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY openbridge/ob_bulkstash:1.40 rclone move /data/path/to/logs/ --include "*.gz" STORAGE:some-storage/some-dir/ --quiet
INFO: There is no CROND configs present. Skipping use of CROND
 New Monit id: 13d31271d4fd8f87bb346fc24e29e2bd
 Stored in '/root/.monit.id'
Starting Monit 5.24.0 daemon with http interface at [localhost]:2849
OK: All processes have completed. rclone service is starting...
```

I looked at `docker-entrypoint.sh` and saw that as for now there is no way to suppress printing of info messagess. Is it possible to add any run option which will disable any info output of container's entrypoint?

**Comment by tspicer** [comment]
Greetings and thank you for the feedback. If you wanted to try you could simply comment out those statements in the `docker-entrypoint.sh` to see if that accomplishes your objectives. If it does then I can take this as an ehancement request.

**Comment by nixikanius** [comment]
@tspicer, thank you for your reply.

Yes, if I comment statements that bother me in `docker-entrypoint.sh`, everything looks great - the output makes completely silent. I can make the pull request with eliminating of all echo statements for normal run of ob_bulkstash.

**Comment by tspicer** [comment]
Adjusted the entry point to remove the use of echo status statements. Should be quiet now. I'm not sure how much can be done about the Monit application notice, but I can take that as another enhancement.

**Comment by nixikanius** [comment]
@tspicer, thank you. I've pulled the latest image of ob_bulkstash and, unfortunately, now see more stdout output than before:

```
# docker run --rm --name=rclone-move-logs -v /path/to/logs:/data/path/to/logs -e RCLONE_CROND_SOURCE_PATH="" -e RCLONE_CROND_DESTINATION_PATH="" -e RCLONE_CONFIG_STORAGE_TYPE="s3" -e RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID=$RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID -e RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY=$RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY openbridge/ob_bulkstash:1.40 rclone move /data/path/to/logs/ --include "*.gz" STORAGE:some-storage/some-dir/ --quiet
set daemon 10
set pidfile /var/run/monit.pid
set statefile /var/run/monit.state
set httpd port 2849 and
    use address localhost
    allow localhost
set logfile syslog
set eventqueue
    basedir /var/run
    slots 100
include /etc/monit.d/*
 New Monit id: 41f5c471ffe84363ef17412f85fcd618
 Stored in '/root/.monit.id'
Starting Monit 5.25.1 daemon with http interface at [localhost]:2849
```

I think, the reason of it is using `tee` utility in monit config generation which came with 1f223413e261ceb3a7f7389f0b5aee36ab458df1 after this issue was created. I do not know the reason why simple config generation was replaced with `tee`, but it looks that its call needs suppression of stdout.

To suppress `monit` output I've created #9.
