### ISSUE TITLE
Suppress monit output in docker entrypoint

### ISSUE THREAD

**Issue by nixikanius** [openbridge/ob_bulkstash#9]
In continuation of #5 I have a need to suppress `monit` output in docker entrypoint, which cames each time a container starts and looks like:

```
# docker run --rm --name=rclone-move-logs -v /path/to/logs:/data/path/to/logs -e RCLONE_CROND_SOURCE_PATH="" -e RCLONE_CROND_DESTINATION_PATH="" -e RCLONE_CONFIG_STORAGE_TYPE="s3" -e RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID=$RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID -e RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY=$RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY openbridge/ob_bulkstash:1.40 rclone move /data/path/to/logs/ --include "*.gz" STORAGE:some-storage/some-dir/ --quiet
...
 New Monit id: 41f5c471ffe84363ef17412f85fcd618
 Stored in '/root/.monit.id'
Starting Monit 5.25.1 daemon with http interface at [localhost]:2849
```

Unfortunately, I do not have any experience with `monit`. Fast googling did not find me any way to suppress the info output of this utility. Nevertheless, it's always possible to send all `monit` output to `/dev/null`. :)

**Comment by tspicer** [comment]
I don't think monit should be running unless crond is activated. Right now it is running as a default. If it is conditional, monit would never show up unless when crond is needed. I will work to make the change.

**Comment by tspicer** [comment]
If you want to test, feel free to edit the `docker-entrypoint.sh` with this block:

```bash
#---------------------------------------------------------------------
# run services
#---------------------------------------------------------------------

function run() {

if [[ ! -z "${RCLONE_CROND_SCHEDULE:-}" ]]; then crond && monit; fi

}

run
exec "$@"
```

This assumes you are not using crond by not setting a required schedule

**Comment by tspicer** [comment]
I tested this and did not get any outputs. Can you confirm?

**Comment by nixikanius** [comment]
Yes, now it is not any info output in ob_bulkstash run at all. Thank you!
